INSERT INTO MEMBER (Name, Age) VALUES ('User 1', 10);
INSERT INTO MEMBER (Name, Age) VALUES ('User 2', 20);
INSERT INTO MEMBER (Name, Age) VALUES ('User 3', 30);
INSERT INTO MEMBER (Name, Age) VALUES ('User 4', 40);
INSERT INTO MEMBER (Name, Age) VALUES ('User 5', 50);